### ISSUE TITLE
[Roadmap] Infrastructure 🚀

### ISSUE THREAD

**Issue by rusty1s** [pyg-team/pyg-lib#22]
* [x] `CMake` Support (#5)
* [x] `CMakeExtension` (#14)
* [x] `clang-format` checks (#12)
* [x] `gtest` test suite (#13)
* [x] Code coverage support (#15, #16, #17, #18)
* [x] Documentation and `readthedocs` support (#19, #20)
* [x] Nightly Builds (#28)
* [ ] GPU Tests
* [ ] `mypy` checks
* [ ] Benchmark/regression tests
* [ ] Package version with + notation (#66)
* [x] `CHANGELOG.md`
